/*
 * Created on 23 M�r 2018 ( Time 23:37:26 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package org.adams.geo.gisweb.business.service.mapping;

import org.adams.geo.gisweb.data.dto.Landschaftselement;
import org.adams.geo.gisweb.data.entities.LandschaftselementEntity;
import org.modelmapper.ModelMapper;
import org.modelmapper.convention.MatchingStrategies;
import org.springframework.stereotype.Component;

/**
 * Mapping between entity beans and display beans.
 */
@Component
public class LandschaftselementServiceMapper extends AbstractServiceMapper {

	/**
	 * ModelMapper : bean to bean mapping library.
	 */
	private ModelMapper modelMapper;

	/**
	 * Constructor.
	 */
	public LandschaftselementServiceMapper() {
		modelMapper = new ModelMapper();
		modelMapper.getConfiguration().setMatchingStrategy(MatchingStrategies.STRICT);
	}

	/**
	 * Mapping from 'LandschaftselementEntity' to 'Landschaftselement'
	 * 
	 * @param landschaftselementEntity
	 */
	public Landschaftselement mapLandschaftselementEntityToLandschaftselement(
			final LandschaftselementEntity landschaftselementEntity) {
		if (landschaftselementEntity == null) {
			return null;
		}

		// --- Generic mapping
		Landschaftselement landschaftselement = map(landschaftselementEntity, Landschaftselement.class);

		return landschaftselement;
	}

	/**
	 * Mapping from 'Landschaftselement' to 'LandschaftselementEntity'
	 * 
	 * @param landschaftselement
	 * @param landschaftselementEntity
	 */
	public void mapLandschaftselementToLandschaftselementEntity(final Landschaftselement landschaftselement,
			final LandschaftselementEntity landschaftselementEntity) {
		if (landschaftselement == null) {
			return;
		}

		// --- Generic mapping
		map(landschaftselement, landschaftselementEntity);

	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	protected ModelMapper getModelMapper() {
		return modelMapper;
	}

	protected void setModelMapper(final ModelMapper modelMapper) {
		this.modelMapper = modelMapper;
	}

}