/*
 * Created on 23 M�r 2018 ( Time 23:37:27 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package org.adams.geo.gisweb.business.service.mapping;

import org.adams.geo.gisweb.data.dto.Teilschlag;
import org.adams.geo.gisweb.data.entities.TeilschlagEntity;
import org.modelmapper.ModelMapper;
import org.modelmapper.convention.MatchingStrategies;
import org.springframework.stereotype.Component;

/**
 * Mapping between entity beans and display beans.
 */
@Component
public class TeilschlagServiceMapper extends AbstractServiceMapper {

	/**
	 * ModelMapper : bean to bean mapping library.
	 */
	private ModelMapper modelMapper;

	/**
	 * Constructor.
	 */
	public TeilschlagServiceMapper() {
		modelMapper = new ModelMapper();
		modelMapper.getConfiguration().setMatchingStrategy(MatchingStrategies.STRICT);
	}

	/**
	 * Mapping from 'TeilschlagEntity' to 'Teilschlag'
	 * 
	 * @param teilschlagEntity
	 */
	public Teilschlag mapTeilschlagEntityToTeilschlag(final TeilschlagEntity teilschlagEntity) {
		if (teilschlagEntity == null) {
			return null;
		}

		// --- Generic mapping
		Teilschlag teilschlag = map(teilschlagEntity, Teilschlag.class);

		return teilschlag;
	}

	/**
	 * Mapping from 'Teilschlag' to 'TeilschlagEntity'
	 * 
	 * @param teilschlag
	 * @param teilschlagEntity
	 */
	public void mapTeilschlagToTeilschlagEntity(final Teilschlag teilschlag, final TeilschlagEntity teilschlagEntity) {
		if (teilschlag == null) {
			return;
		}

		// --- Generic mapping
		map(teilschlag, teilschlagEntity);

	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	protected ModelMapper getModelMapper() {
		return modelMapper;
	}

	protected void setModelMapper(final ModelMapper modelMapper) {
		this.modelMapper = modelMapper;
	}

}