/*
 * Created on 23 M�r 2018 ( Time 23:37:27 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package org.adams.geo.gisweb.business.service.mapping;

import org.adams.geo.gisweb.data.dto.Teillandschaftselement;
import org.adams.geo.gisweb.data.entities.TeillandschaftselementEntity;
import org.modelmapper.ModelMapper;
import org.modelmapper.convention.MatchingStrategies;
import org.springframework.stereotype.Component;

/**
 * Mapping between entity beans and display beans.
 */
@Component
public class TeillandschaftselementServiceMapper extends AbstractServiceMapper {

	/**
	 * ModelMapper : bean to bean mapping library.
	 */
	private ModelMapper modelMapper;

	/**
	 * Constructor.
	 */
	public TeillandschaftselementServiceMapper() {
		modelMapper = new ModelMapper();
		modelMapper.getConfiguration().setMatchingStrategy(MatchingStrategies.STRICT);
	}

	/**
	 * Mapping from 'TeillandschaftselementEntity' to 'Teillandschaftselement'
	 * 
	 * @param teillandschaftselementEntity
	 */
	public Teillandschaftselement mapTeillandschaftselementEntityToTeillandschaftselement(
			final TeillandschaftselementEntity teillandschaftselementEntity) {
		if (teillandschaftselementEntity == null) {
			return null;
		}

		// --- Generic mapping
		Teillandschaftselement teillandschaftselement = map(teillandschaftselementEntity, Teillandschaftselement.class);

		return teillandschaftselement;
	}

	/**
	 * Mapping from 'Teillandschaftselement' to 'TeillandschaftselementEntity'
	 * 
	 * @param teillandschaftselement
	 * @param teillandschaftselementEntity
	 */
	public void mapTeillandschaftselementToTeillandschaftselementEntity(
			final Teillandschaftselement teillandschaftselement,
			final TeillandschaftselementEntity teillandschaftselementEntity) {
		if (teillandschaftselement == null) {
			return;
		}

		// --- Generic mapping
		map(teillandschaftselement, teillandschaftselementEntity);

	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	protected ModelMapper getModelMapper() {
		return modelMapper;
	}

	protected void setModelMapper(final ModelMapper modelMapper) {
		this.modelMapper = modelMapper;
	}

}