/*
 * Java bean class for entity table teillandschaftselement
 * Created on 23 M�r 2018 ( Date ISO 2018-03-23 - Time 23:44:21 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */

package org.adams.geo.gisweb.data.dto;

import java.io.Serializable;
import java.math.BigDecimal;

import com.vividsolutions.jts.geom.Geometry;

/**
 * Entity bean for table "teillandschaftselement"
 *
 * @author Telosys Tools Generator
 *
 */
public class Teillandschaftselement implements Serializable {
	private static final long serialVersionUID = 1L;

	private Integer gid; // Primary Key

	private String flik;
	private String flek;
	private BigDecimal nrle;
	private BigDecimal schlagnr;
	private Geometry geom;

	/**
	 * Default constructor
	 */
	public Teillandschaftselement() {
		super();
	}

	// ----------------------------------------------------------------------
	// GETTER(S) & SETTER(S) FOR THE PRIMARY KEY
	// ----------------------------------------------------------------------
	/**
	 * Set the "gid" field value This field is mapped on the database column "gid" (
	 * type "serial", NotNull : true )
	 *
	 * @param gid
	 */
	public void setGid(final Integer gid) {
		this.gid = gid;
	}

	/**
	 * Get the "gid" field value This field is mapped on the database column "gid" (
	 * type "serial", NotNull : true )
	 *
	 * @return the field value
	 */
	public Integer getGid() {
		return gid;
	}

	// ----------------------------------------------------------------------
	// GETTER(S) & SETTER(S) FOR DATA FIELDS
	// ----------------------------------------------------------------------
	// --- DATABASE MAPPING : flik ( varchar )
	/**
	 * Set the "flik" field value This field is mapped on the database column "flik"
	 * ( type "varchar", NotNull : false )
	 *
	 * @param flik
	 */
	public void setFlik(final String flik) {
		this.flik = flik;
	}

	/**
	 * Get the "flik" field value This field is mapped on the database column "flik"
	 * ( type "varchar", NotNull : false )
	 *
	 * @return the field value
	 */
	public String getFlik() {
		return flik;
	}

	// --- DATABASE MAPPING : flek ( varchar )
	/**
	 * Set the "flek" field value This field is mapped on the database column "flek"
	 * ( type "varchar", NotNull : false )
	 *
	 * @param flek
	 */
	public void setFlek(final String flek) {
		this.flek = flek;
	}

	/**
	 * Get the "flek" field value This field is mapped on the database column "flek"
	 * ( type "varchar", NotNull : false )
	 *
	 * @return the field value
	 */
	public String getFlek() {
		return flek;
	}

	// --- DATABASE MAPPING : nrle ( numeric )
	/**
	 * Set the "nrle" field value This field is mapped on the database column "nrle"
	 * ( type "numeric", NotNull : false )
	 *
	 * @param nrle
	 */
	public void setNrle(final BigDecimal nrle) {
		this.nrle = nrle;
	}

	/**
	 * Get the "nrle" field value This field is mapped on the database column "nrle"
	 * ( type "numeric", NotNull : false )
	 *
	 * @return the field value
	 */
	public BigDecimal getNrle() {
		return nrle;
	}

	// --- DATABASE MAPPING : schlagnr ( numeric )
	/**
	 * Set the "schlagnr" field value This field is mapped on the database column
	 * "schlagnr" ( type "numeric", NotNull : false )
	 *
	 * @param schlagnr
	 */
	public void setSchlagnr(final BigDecimal schlagnr) {
		this.schlagnr = schlagnr;
	}

	/**
	 * Get the "schlagnr" field value This field is mapped on the database column
	 * "schlagnr" ( type "numeric", NotNull : false )
	 *
	 * @return the field value
	 */
	public BigDecimal getSchlagnr() {
		return schlagnr;
	}

	// --- DATABASE MAPPING : geom ( geometry )
	/**
	 * Set the "geom" field value This field is mapped on the database column "geom"
	 * ( type "geometry", NotNull : false )
	 *
	 * @param geom
	 */
	public void setGeom(final Geometry geom) {
		this.geom = geom;
	}

	/**
	 * Get the "geom" field value This field is mapped on the database column "geom"
	 * ( type "geometry", NotNull : false )
	 *
	 * @return the field value
	 */
	public Geometry getGeom() {
		return geom;
	}

	// ----------------------------------------------------------------------
	// toString METHOD
	// ----------------------------------------------------------------------
	@Override
	public String toString() {
		StringBuilder sb = new StringBuilder();
		sb.append(gid);
		sb.append("|");
		sb.append(flik);
		sb.append("|");
		sb.append(flek);
		sb.append("|");
		sb.append(nrle);
		sb.append("|");
		sb.append(schlagnr);
		sb.append("|");
		sb.append(geom);
		return sb.toString();
	}

}
