/*
 * Created on 23 M�r 2018 ( Time 23:37:26 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package org.adams.geo.gisweb.business.service;

import java.util.List;

import org.adams.geo.gisweb.data.dto.Feldblock;
import org.springframework.data.domain.Page;
import org.springframework.data.domain.Pageable;

import com.querydsl.core.types.Predicate;

/**
 * Business Service Interface for entity Feldblock.
 */
public interface FeldblockService {

	/**
	 * Loads an entity from the database using its Primary Key
	 *
	 * @param gid
	 * @return entity
	 */
	Feldblock findById(Integer gid);

	/**
	 * Loads all entities.
	 *
	 * @return all entities
	 */
	List<Feldblock> findAll();

	/**
	 * Saves the given entity in the database (create or update)
	 *
	 * @param entity
	 * @return entity
	 */
	Feldblock save(Feldblock entity);

	/**
	 * Updates the given entity in the database
	 *
	 * @param entity
	 * @return
	 */
	Feldblock update(Feldblock entity);

	/**
	 * Creates the given entity in the database
	 *
	 * @param entity
	 * @return
	 */
	Feldblock create(Feldblock entity);

	/**
	 * Deletes an entity using its Primary Key
	 *
	 * @param gid
	 */
	void delete(Integer gid);

	/**
	 * Gets a page of entities fulfilling the predicate.
	 * 
	 * @param predicate
	 * @param pageable
	 * @return
	 */
	Page<Feldblock> findAll(final Predicate predicate, final Pageable pageable);

}
