/*
 * Created on 23 M�r 2018 ( Time 23:37:27 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package org.adams.geo.gisweb.business.service.mapping;

import static org.junit.Assert.assertEquals;

import org.adams.geo.gisweb.data.dto.Schlag;
import org.adams.geo.gisweb.data.entities.SchlagEntity;
import org.adams.geo.gisweb.test.MockValues;
import org.junit.Before;
import org.junit.BeforeClass;
import org.junit.Test;
import org.modelmapper.ModelMapper;
import org.modelmapper.convention.MatchingStrategies;

/**
 * Test : Mapping between entity beans and display beans.
 */
public class SchlagServiceMapperTest {

	private SchlagServiceMapper schlagServiceMapper;

	private static ModelMapper modelMapper = new ModelMapper();

	private MockValues mockValues = new MockValues();

	@BeforeClass
	public static void setUp() {
		modelMapper.getConfiguration().setMatchingStrategy(MatchingStrategies.STRICT);
	}

	@Before
	public void before() {
		schlagServiceMapper = new SchlagServiceMapper();
		schlagServiceMapper.setModelMapper(modelMapper);
	}

	/**
	 * Mapping from 'SchlagEntity' to 'Schlag'
	 *
	 * @param schlagEntity
	 */
	@Test
	public void testMapSchlagEntityToSchlag() {
		// Given
		SchlagEntity schlagEntity = new SchlagEntity();
		schlagEntity.setFlik(mockValues.nextString(254));
		schlagEntity.setSchlagnr(mockValues.nextBigDecimal());
		schlagEntity.setKulturcode(mockValues.nextString(100));
		schlagEntity.setAntjahr(mockValues.nextLong());
		schlagEntity.setGemFl(mockValues.nextDouble());
		schlagEntity.setGeom(mockValues.nextGeometry());
		// When
		Schlag schlag = schlagServiceMapper.mapSchlagEntityToSchlag(schlagEntity);

		// Then
		assertEquals(schlagEntity.getFlik(), schlag.getFlik());
		assertEquals(schlagEntity.getSchlagnr(), schlag.getSchlagnr());
		assertEquals(schlagEntity.getKulturcode(), schlag.getKulturcode());
		assertEquals(schlagEntity.getAntjahr(), schlag.getAntjahr());
		assertEquals(schlagEntity.getGemFl(), schlag.getGemFl());
		assertEquals(schlagEntity.getGeom(), schlag.getGeom());
	}

	/**
	 * Test : Mapping from 'Schlag' to 'SchlagEntity'
	 */
	@Test
	public void testMapSchlagToSchlagEntity() {
		// Given
		Schlag schlag = new Schlag();
		schlag.setFlik(mockValues.nextString(254));
		schlag.setSchlagnr(mockValues.nextBigDecimal());
		schlag.setKulturcode(mockValues.nextString(100));
		schlag.setAntjahr(mockValues.nextLong());
		schlag.setGemFl(mockValues.nextDouble());
		schlag.setGeom(mockValues.nextGeometry());

		SchlagEntity schlagEntity = new SchlagEntity();

		// When
		schlagServiceMapper.mapSchlagToSchlagEntity(schlag, schlagEntity);

		// Then
		assertEquals(schlag.getFlik(), schlagEntity.getFlik());
		assertEquals(schlag.getSchlagnr(), schlagEntity.getSchlagnr());
		assertEquals(schlag.getKulturcode(), schlagEntity.getKulturcode());
		assertEquals(schlag.getAntjahr(), schlagEntity.getAntjahr());
		assertEquals(schlag.getGemFl(), schlagEntity.getGemFl());
		assertEquals(schlag.getGeom(), schlagEntity.getGeom());
	}

}