/*
 * Created on 24 M�r 2018 ( Time 16:32:44 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package org.adams.geo.gisweb.rest.controller;

import java.util.List;

import javax.annotation.Resource;

import org.adams.geo.gisweb.business.service.LandschaftselementService;
import org.adams.geo.gisweb.data.dto.Landschaftselement;
import org.springframework.http.HttpStatus;
import org.springframework.http.MediaType;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.*;

/**
 * Spring MVC controller for 'Landschaftselement' management.
 */
@RestController
public class LandschaftselementRestController {

	@Resource
	private LandschaftselementService landschaftselementService;

	@RequestMapping(value = "/landschaftselement", method = RequestMethod.GET, produces = MediaType.APPLICATION_JSON_VALUE)
	@ResponseStatus(HttpStatus.OK)
	@ResponseBody
	public List<Landschaftselement> findAll() {
		return landschaftselementService.findAll();
	}

	@RequestMapping(value = "/landschaftselement/{gid}", method = RequestMethod.GET, produces = MediaType.APPLICATION_JSON_VALUE)
	@ResponseStatus(HttpStatus.OK)
	@ResponseBody
	public Landschaftselement findOne(@PathVariable("gid") final Integer gid) {
		return landschaftselementService.findById(gid);
	}

	@RequestMapping(value = "/landschaftselement", method = RequestMethod.POST, produces = MediaType.APPLICATION_JSON_VALUE)
	@ResponseStatus(HttpStatus.OK)
	@ResponseBody
	public Landschaftselement create(@RequestBody final Landschaftselement landschaftselement) {
		return landschaftselementService.create(landschaftselement);
	}

	@RequestMapping(value = "/landschaftselement/{gid}", method = RequestMethod.PUT, produces = MediaType.APPLICATION_JSON_VALUE)
	@ResponseStatus(HttpStatus.OK)
	@ResponseBody
	public Landschaftselement update(@PathVariable("gid") final Integer gid,
			@RequestBody final Landschaftselement landschaftselement) {
		return landschaftselementService.update(landschaftselement);
	}

	@RequestMapping(value = "/landschaftselement/{gid}", method = RequestMethod.DELETE, produces = MediaType.APPLICATION_JSON_VALUE)
	@ResponseStatus(HttpStatus.OK)
	@ResponseBody
	public void delete(@PathVariable("gid") final Integer gid) {
		landschaftselementService.delete(gid);
	}

}
