/*
 * Created on 24 M�r 2018 ( Time 16:32:44 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package org.adams.geo.gisweb.web.controller;

import java.util.List;

import javax.annotation.Resource;
import javax.servlet.http.HttpServletRequest;
import javax.validation.Valid;

//--- Services
import org.adams.geo.gisweb.business.service.SchlagService;
import org.adams.geo.gisweb.data.dto.Schlag;
//--- Common classes
import org.adams.geo.gisweb.web.common.AbstractController;
import org.adams.geo.gisweb.web.common.FormMode;
import org.adams.geo.gisweb.web.common.Message;
import org.adams.geo.gisweb.web.common.MessageHelper;
import org.adams.geo.gisweb.web.common.MessageType;
import org.springframework.stereotype.Controller;
import org.springframework.ui.Model;
import org.springframework.validation.BindingResult;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.servlet.mvc.support.RedirectAttributes;

/**
 * Spring MVC controller for 'Schlag' management.
 */
@Controller
@RequestMapping("/schlag")
public class SchlagController extends AbstractController {

	// --- Variables names ( to be used in JSP with Expression Language )
	private static final String MAIN_ENTITY_NAME = "schlag";
	private static final String MAIN_LIST_NAME = "list";

	// --- JSP pages names ( View name in the MVC model )
	private static final String JSP_FORM = "schlag/form";
	private static final String JSP_LIST = "schlag/list";

	// --- SAVE ACTION ( in the HTML form )
	private static final String SAVE_ACTION_CREATE = "/schlag/create";
	private static final String SAVE_ACTION_UPDATE = "/schlag/update";

	// --- Main entity service
	@Resource
	private SchlagService schlagService; // Injected by Spring
	// --- Other service(s)

	@Resource
	private MessageHelper messageHelper;

	// --------------------------------------------------------------------------------------
	/**
	 * Default constructor
	 */
	public SchlagController() {
		super(SchlagController.class, MAIN_ENTITY_NAME);
		log("SchlagController created.");
	}

	// --------------------------------------------------------------------------------------
	// Spring MVC model management
	// --------------------------------------------------------------------------------------

	/**
	 * Populates the Spring MVC model with the given entity and eventually other
	 * useful data
	 * 
	 * @param model
	 * @param schlag
	 */
	private void populateModel(final Model model, final Schlag schlag, final FormMode formMode) {
		// --- Main entity
		model.addAttribute(MAIN_ENTITY_NAME, schlag);
		if (formMode == FormMode.CREATE) {
			model.addAttribute(MODE, MODE_CREATE); // The form is in "create" mode
			model.addAttribute(SAVE_ACTION, SAVE_ACTION_CREATE);
			// --- Other data useful in this screen in "create" mode (all fields)
		} else if (formMode == FormMode.UPDATE) {
			model.addAttribute(MODE, MODE_UPDATE); // The form is in "update" mode
			model.addAttribute(SAVE_ACTION, SAVE_ACTION_UPDATE);
			// --- Other data useful in this screen in "update" mode (only non-pk fields)
		}
	}

	// --------------------------------------------------------------------------------------
	// Request mapping
	// --------------------------------------------------------------------------------------
	/**
	 * Shows a list with all the occurrences of Schlag found in the database
	 * 
	 * @param model
	 *            Spring MVC model
	 * @return
	 */
	@RequestMapping()
	public String list(final Model model) {
		log("Action 'list'");
		List<Schlag> list = schlagService.findAll();
		model.addAttribute(MAIN_LIST_NAME, list);
		return JSP_LIST;
	}

	/**
	 * Shows a form page in order to create a new Schlag
	 * 
	 * @param model
	 *            Spring MVC model
	 * @return
	 */
	@RequestMapping("/form")
	public String formForCreate(final Model model) {
		log("Action 'formForCreate'");
		// --- Populates the model with a new instance
		Schlag schlag = new Schlag();
		populateModel(model, schlag, FormMode.CREATE);
		return JSP_FORM;
	}

	/**
	 * Shows a form page in order to update an existing Schlag
	 * 
	 * @param model
	 *            Spring MVC model
	 * @param gid
	 *            primary key element
	 * @return
	 */
	@RequestMapping(value = "/form/{gid}")
	public String formForUpdate(final Model model, @PathVariable("gid") final Integer gid) {
		log("Action 'formForUpdate'");
		// --- Search the entity by its primary key and stores it in the model
		Schlag schlag = schlagService.findById(gid);
		populateModel(model, schlag, FormMode.UPDATE);
		return JSP_FORM;
	}

	/**
	 * 'CREATE' action processing. <br>
	 * This action is based on the 'Post/Redirect/Get (PRG)' pattern, so it ends by
	 * 'http redirect'<br>
	 * 
	 * @param schlag
	 *            entity to be created
	 * @param bindingResult
	 *            Spring MVC binding result
	 * @param model
	 *            Spring MVC model
	 * @param redirectAttributes
	 *            Spring MVC redirect attributes
	 * @param httpServletRequest
	 * @return
	 */
	@RequestMapping(value = "/create") // GET or POST
	public String create(@Valid final Schlag schlag, final BindingResult bindingResult, final Model model,
			final RedirectAttributes redirectAttributes, final HttpServletRequest httpServletRequest) {
		log("Action 'create'");
		try {
			if (!bindingResult.hasErrors()) {
				Schlag schlagCreated = schlagService.create(schlag);
				model.addAttribute(MAIN_ENTITY_NAME, schlagCreated);

				// ---
				messageHelper.addMessage(redirectAttributes, new Message(MessageType.SUCCESS, "save.ok"));
				return redirectToForm(httpServletRequest, schlag.getGid());
			} else {
				populateModel(model, schlag, FormMode.CREATE);
				return JSP_FORM;
			}
		} catch (Exception e) {
			log("Action 'create' : Exception - " + e.getMessage());
			messageHelper.addException(model, "schlag.error.create", e);
			populateModel(model, schlag, FormMode.CREATE);
			return JSP_FORM;
		}
	}

	/**
	 * 'UPDATE' action processing. <br>
	 * This action is based on the 'Post/Redirect/Get (PRG)' pattern, so it ends by
	 * 'http redirect'<br>
	 * 
	 * @param schlag
	 *            entity to be updated
	 * @param bindingResult
	 *            Spring MVC binding result
	 * @param model
	 *            Spring MVC model
	 * @param redirectAttributes
	 *            Spring MVC redirect attributes
	 * @param httpServletRequest
	 * @return
	 */
	@RequestMapping(value = "/update") // GET or POST
	public String update(@Valid final Schlag schlag, final BindingResult bindingResult, final Model model,
			final RedirectAttributes redirectAttributes, final HttpServletRequest httpServletRequest) {
		log("Action 'update'");
		try {
			if (!bindingResult.hasErrors()) {
				// --- Perform database operations
				Schlag schlagSaved = schlagService.update(schlag);
				model.addAttribute(MAIN_ENTITY_NAME, schlagSaved);
				// --- Set the result message
				messageHelper.addMessage(redirectAttributes, new Message(MessageType.SUCCESS, "save.ok"));
				log("Action 'update' : update done - redirect");
				return redirectToForm(httpServletRequest, schlag.getGid());
			} else {
				log("Action 'update' : binding errors");
				populateModel(model, schlag, FormMode.UPDATE);
				return JSP_FORM;
			}
		} catch (Exception e) {
			messageHelper.addException(model, "schlag.error.update", e);
			log("Action 'update' : Exception - " + e.getMessage());
			populateModel(model, schlag, FormMode.UPDATE);
			return JSP_FORM;
		}
	}

	/**
	 * 'DELETE' action processing. <br>
	 * This action is based on the 'Post/Redirect/Get (PRG)' pattern, so it ends by
	 * 'http redirect'<br>
	 * 
	 * @param redirectAttributes
	 * @param gid
	 *            primary key element
	 * @return
	 */
	@RequestMapping(value = "/delete/{gid}") // GET or POST
	public String delete(final RedirectAttributes redirectAttributes, @PathVariable("gid") final Integer gid) {
		log("Action 'delete'");
		try {
			schlagService.delete(gid);
			// --- Set the result message
			messageHelper.addMessage(redirectAttributes, new Message(MessageType.SUCCESS, "delete.ok"));
		} catch (Exception e) {
			messageHelper.addException(redirectAttributes, "schlag.error.delete", e);
		}
		return redirectToList();
	}

}
